HOST: 0.0.0.0
PORT: 8080
NODE_ENV: development
APP_URL: http://${HOST}:${PORT}
CACHE_VIEWS: false
APP_KEY: gypVEVEIvNmjCb0BvkrMn5qLnGwIfleS
DB_CONNECTION: sqlite
DB_HOST: 127.0.0.1
DB_PORT: 5432
DB_USER: postgres
DB_PASSWORD: 123qwe
DB_DATABASE: notadd
SESSION_DRIVER: cookie